# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# in the templates via {{ site.myvariable }}.
title: Mental Changelog
email: riccardi.dalexis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mainly a brain dump about things I encounter while working. Otherwise, I probably
  would forget them...
baseurl: "/mental_changelog.github.io" # the subpath of your site, e.g. /blog
url: "https://rod7760.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rod7760

# Build settings
markdown: kramdown
#remote_theme: jekyll/minima
theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
